config/routes.rb
Isk::Application.routes.draw do
  root 'search#index'
  get   '/search' => 'search#index'
  post  '/search' => 'search#query', as: :submit_search
  get   '/search/advanced' => 'search#advanced', as: :advanced_search
  resources :titles
  resources :authors
  resources :books do
    get :sold, on: :member
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  self.table_name = "author"

  has_many :author_titles
  has_many :titles, :through => :author_titles
end

app/models/author_title.rb
class AuthorTitle < ActiveRecord::Base
  self.table_name = "author_title"

  belongs_to :author
  belongs_to :title
end

app/models/book.rb
class Book < ActiveRecord::Base
  self.table_name = "book"

  belongs_to :title
  belongs_to :location

  def self.sold
    where(status: "SOLD")
  end

  def self.stock
    where(status: "STOCK")
  end

  def self.deleted
    where(status: "DELETED")
  end

  def our_price
    sprintf "$%.2f", ourprice
  end

  def sold!
    update_attributes status: "SOLD"
  end

end

app/models/book_image.rb
class BookImage < ActiveRecord::Base
  belongs_to :book
  mount_uploader :image_file, ImageFileUploader

  def attach_image!(image_file_url)
    if image_file.blank?
      self.remote_image_file_url = image_file_url 
      self.save! rescue nil
    end
  end
end

app/models/book_inventory.rb
class BookInventory < ActiveRecord::Base
  self.table_name = "book_inventory"
end

app/models/kind.rb
class Kind < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
  self.table_name = "location"

  def name
    self.location_name
  end
end

app/models/ranked_inventory.rb
class RankedInventory < ActiveRecord::Base
  self.table_name = "ranked_inventory"
end

app/models/status.rb
class Status < ActiveRecord::Base
  self.table_name = "status"
end

app/models/title.rb
require 'open-uri'

class Title < ActiveRecord::Base
  self.table_name = "title"

  include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping do
    indexes :id, index: :not_analyzed

    indexes :booktitle,    analyzer: 'snowball', boost: 100
    indexes :publisher,    analyzer: 'snowball'
    indexes :author_names, analyzer: 'snowball', as: "author_names"
  end


  has_many :author_titles
  has_many :authors, :through => :author_titles
  has_many :books

  has_one :book_image

  def attach_image!
    if self.book_image.blank?
      book_image = BookImage.create!(title_id: id)
      book_image.attach_image!(image_file_url)
    elsif self.book_image.image_file.blank?
      self.book_image.attach_image!(image_file_url)
    end
  end

  def image_url
    if book_image.present?
      book_image.image_file.url rescue ""
    else
      ""
    end
  end

  def image_file_url
    "http://www2.alibris-static.com/isbn/#{isbn}.gif"
  end

  def available_copies
    books.where(status: 'STOCK')
  end

  def locations
    books.map {|b| b.location.name rescue nil }.uniq.reject(&:blank?)
  end

  def self.inheritance_column
    :none
  end

  def self.t
    arel_table
  end

  def self.search_book_name(term)
    t[:booktitle].matches("%#{term}%")
  end

  def self.search_publisher(term)
    t[:publisher].matches("%#{term}%")
  end

  def self.search_isbn(term)
    t[:isbn].matches("%#{term}%").or(t[:isbn13].matches("%#{term}%"))
  end

  def self.search_author_name(term)
    a = Author.arel_table
    a[:author_name].matches("%#{term}%")
  end

  def self.search(term)
    queries = term.split(' ').map {|t| queries_for(t) }

    where(queries.flatten.reduce(:or)).includes(:authors).references(:authors)
  end

  def self.queries_for(string)
    if string =~ /^[0-9]*$/
      term = string[0..12]
    else
      term = string
    end

    [
     search_book_name(term),
     # search_publisher(term),
     search_isbn(term),
     search_author_name(term)
    ]
  end

  def author_names
    authors.map(&:author_name).join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def sold
    @book = Book.find(params[:id])
    @book.sold!
    redirect_to :back
  end

  def edit
  end

  def update
  end

  def new
  end

  def create
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @titles = Title.order("id DESC").paginate(page: params[:page])
  end

  def query
    @titles = Title.search(params[:term]).paginate(page: params[:page])
    render action: "results"
  end

  def advanced
    @titles = Title.advanced_search(params)
    render action: "results"
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def show
    @title = Title.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def available_copies(title)
    c = title.available_copies.count
    if c.zero?
      %Q{<span style="color: red">None</span>}.html_safe
    else
      %Q{<span style="color: green">#{c}</span>}.html_safe
    end
  end

  def authors(title)
    title.authors.map {|a| link_to a.author_name, author_path(a) }.join(", ").html_safe
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/authors/show.html.erb
<div>
  <h1><%= @author.author_name %></h1>

  <div>
    <h3>Books (<%= @author.titles.count %>)</h3>
    <table class="table table-striped table-bordered">
      <tr>
	<th>Book Title</th>
	<th>Publisher</th>
	<th>ISBN</th>
      </tr>
      <% @author.titles.each do |title| %>
	<tr>
	  <td><%= link_to title.booktitle, title_path(title) %></td>
	  <td><%= title.publisher %></td>
	  <td><%= title.isbn %></td>
	</tr>
      <% end %>
    </table>
  </div>
</div>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/sold.html.erb
<h1>Books#sold</h1>
<p>Find me in app/views/books/sold.html.erb</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ISK" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container" style="width: 70em;">
          <a class="brand" href="/">
	    ISK2 <b>BETA</b>
	  </a>
        </div>
      </div>
    </div>

    <div class="container" style="width: 70em;">
      <div class="row" style="padding-top: 4em;">
	<div class="pull-left">
	  <%= form_tag submit_search_path, class: "navbar-form input-append" do %>
	    <input style="width: 55em;" name="term" id="term" value="<%= params[:term] %>" type="text" placeholder="Type any book title, author, or ISBN"></input>
	    <input class="add-on btn" type="submit" style="margin-top: 5px; height: 30px;" value="Search"></input>
	  <% end %>

	  <div style="margin-top: 1em;">
	    <%#= link_to "Advanced Search", advanced_search_path, class: "pull-right" %>
	  </div>
	</div>
      </div>

      <div class="row">
        <div style="padding-top: 4em;">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <div style="color: #aaa; font-size: 11px; text-align: right;">
	Please contact <%= link_to "robinhoode@gmail.com", "mailto:robinhoode@gmail.com" %> for any issues
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/search/index.html.erb
<h1>Recently Added Titles</h1>

<table class="table table-striped table-bordered" style="width: 100%;">
  <tr>
    <th></th>
    <th>Book Title</th>
    <th>Authors</th>
    <th>Copies</th>
  </tr>

  <% @titles.each do |title| %>
    <tr>
      <td><%= image_tag title.image_url, style: "min-width: 64px; width: 64px;" %></td>
      <td><%= link_to title.booktitle, title_path(title) %></td>
      <td><%= authors(title) %></td>
      <td style="text-align: center;">
	      <%= available_copies(title) %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @titles %>

app/views/search/results.html.erb
<% unless params[:term].blank? %>
  <div style="margin-bottom: 4em; margin-top: 1em;">
    <div style="font-size: 2em;" class="pull-left">
      Search results for <b><%= params[:term] %></b>
    </div>
  </div>
<% end %>

<table class="table table-striped table-bordered" style="width: 100%;">
  <tr>
    <th></th>
    <th>Book Title</th>
    <th>Author(s)</th>
    <th>Section</th>
    <th>Copies</th>
  </tr>

  <% @titles.each do |title| %>
    <tr>
      <td><%= image_tag title.image_url, style: "min-width: 64px; width: 64px;" %></td>
      <td><%= link_to title.booktitle, title_path(title) %></td>
      <td><%= authors(title) %></td>
      <td><%= title.locations.join(", ").html_safe %></td>
      <td style="text-align: center;">
	      <%= available_copies(title) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/titles/_book_row.html.erb
<tr>
  <td><%= book.status %></td>
  <td><%= book.location.location_name %></td>
  <td><%= book.our_price %></td>
  <td>
    <% if book.status == "STOCK" %>
      <%= link_to "Mark as Sold", sold_book_path(book), class: "btn pull-right", confirm: "Are you sure?" %>
    <% end %>
  </td>
</tr>

app/views/titles/show.html.erb
<div>
  <div class="row">
    <div class="span2">
      <% unless @title.image_url.blank? %>
        <%= image_tag @title.image_url %>
      <% end %>
    </div>
    <div class="span7">
      <h1><%= @title.booktitle %></h1>

      <% unless @title.authors.count.zero? %>
	      <h4>By
	        <%= @title.authors.map {|a| link_to a.author_name, author_path(a) }.join(", ").html_safe %>
	      </h4>
      <% end %>

      <% unless @title.publisher.blank? %>
	      <h4>Publisher: <%= @title.publisher %></h4>
      <% end %>

      <% unless @title.isbn.blank? %>
	      <h4>ISBN: <%= @title.isbn %></h4>
      <% end %>
    </div>
  </div>

  <div class="row">
    <h3>Copies (<%= @title.books.count %>)</h3>
    <table class="table table-striped table-bordered">
      <tr>
	      <th>Status</th>
	      <th>Location</th>
	      <th>Price</th>
	      <th></th>
      </tr>
      <% @title.books.stock.each do |book| %>
        <%= render partial: "titles/book_row", locals: {book: book} %>
      <% end %>

      <% @title.books.sold.each do |book| %>
        <%= render partial: "titles/book_row", locals: {book: book} %>
      <% end %>

      <% @title.books.deleted.each do |book| %>
        <%= render partial: "titles/book_row", locals: {book: book} %>
      <% end %>
    </table>
  </div>
</div>